# Generated by Django 3.0.6 on 2020-05-09 10:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200509_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 10, 24, 17, 75084, tzinfo=utc), verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
