# Generated by Django 3.0.6 on 2020-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200515_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date', '-updated', '-timestamp']},
        ),
    ]
